language: python
# python 3.5 and later can do --install-binary for numpy,scipy
python:
    - "3.5"
    - "3.6"

# need gfortran to buid multinest
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - libblas-dev
      - liblapack-dev

# command to install dependencies, numpy/scipy binaries
# are quicker and avoid lapack issues
install:
    - pip install --only-binary=numpy,scipy numpy scipy
    - pip install mysql-connector==2.1.4
    - pip install .

# run pytest tests, build multinest first
script:
    - export FC=/usr/bin/gfortran-6
    - git clone https://github.com/JohannesBuchner/MultiNest.git
    - cd MultiNest/build
    - cmake ..
    - make
    - cd ../../
    - export LD_LIBRARY_PATH=MultiNest/lib
    - export DYLD_LIBRARY_PATH=MultiNest/lib
    - pytest
